### ISSUE TITLE
wakaru.land 取得

### ISSUE THREAD

**Issue by masui** [napo0703/WakaruLand#10]
高いけど...

**Comment by masui** [comment]
URLは wakaru.land/masui とか?

**Comment by napo0703** [comment]
とりあえず https://wakaruland.com でアクセスできるようにはしました。

**Comment by masui** [comment]
value-domainだと3980円

**Comment by masui** [comment]
取れないんじゃしょうがないね

**Comment by napo0703** [comment]
取れますが高い
![](https://i.gyazo.com/eeef9aeaf0868887ffb3b0e5f23944ec.png)

**Comment by shokai** [comment]
2かずすけもするのか

**Comment by napo0703** [comment]
でもかずすけで1年間に使う額より安い

**Comment by shokai** [comment]
🍖  ◀️  🔥 ◀️   🐄
