### ISSUE TITLE
しばらくリアクションしなかったら一覧からリアクションを消す

### ISSUE THREAD

**Issue by napo0703** [napo0703/WakaruLand#11]
30分前の「神」とか残ってるとよくわからんど

**Comment by masui** [comment]
- 1分ぐらいたったら消してしまうべき
- もっと短くてもいいかも

**Comment by napo0703** [comment]
https://github.com/napo0703/WakaruLand/pull/17 で30秒で消すのを実装しました。
しかし、WakaruLandにフォーカスが当たっていないと上手く動きません(>_<)。
30秒のカウントに使用している[setInterval](https://developer.mozilla.org/ja/docs/Web/API/Window/setInterval)の処理が実行されずにキューとして溜まっているようです。
フォーカスが当たってなくても30秒をカウントする方法があったら教えていただきたいです。

**Comment by masui** [comment]
- 一時的感想 (e.g. 「わかる!」) と、現在の状況 (e.g. 「会議中」) などを両方扱えるようにしたい。前者は30秒で消えて良いが後者はずっと表示されててほしい。
- そうなってれば、知人の状況リストをずっと表示しておけるので便利だと思う。
- 人でなくてもよい。(e.g. 「トイレ空いてる」)

**Comment by masui** [comment]
これは通知システムの新機軸になるのでは??

**Comment by napo0703** [comment]
cbe64be で実装した。
続きは #26 で。
