### ISSUE TITLE
入力デバイスを作る

### ISSUE THREAD

**Issue by napo0703** [napo0703/WakaruLand#14]

**Comment by napo0703** [comment]
「わからん」と書いてあるオブジェクトをUSBで繋ぐと「わからん」と表示される

**Comment by masui** [comment]
地団駄を践むと「じだんだ」と表示される

**Comment by napo0703** [comment]
「膝を打つ」と「なるほど」
「頭を抱える」と「たすけて」
「首をひねる」と「わからん」

**Comment by masui** [comment]
渋い顔をすると渋い顔文字が表示される

**Comment by napo0703** [comment]
とりあえずテンキーで専用入力ボタンを作ってみる

**Comment by shokai** [comment]
ワイヤレスマウスを安価な物理ボタンとして使う
http://qiita.com/uiureo/items/a4158939e605b2b0c501

**Comment by napo0703** [comment]
テンキー作った。
これで`/dev/input/event0`見ればいけそう。

![](https://i.gyazo.com/d1988eeed29efe890a3ef6e4a5fb06a5.jpg)

**Comment by shokai** [comment]
![image](https://cloud.githubusercontent.com/assets/34204/17861509/57a9fbfe-68cc-11e6-96ec-4de6d3220163.png)

**Comment by shokai** [comment]
numlockがすげーいい所にある

**Comment by napo0703** [comment]
MacでLinuxの`/dev/input/event0`にあたるものがどこにあるのか
<img src="https://i.gyazo.com/1bc0ae9981d968a5014ebc5bd604b07e.png" width="128">

**Comment by shokai** [comment]
そんなものはない！

**Comment by napo0703** [comment]
<img src="https://i.gyazo.com/4a7203e6b3b54a5f38ac4c4020104c9c.png" width=128>
