### ISSUE TITLE
顔アイコン表示

### ISSUE THREAD

**Issue by masui** [napo0703/WakaruLand#16]
- TwitterやFacebookに登録されてる顔アイコンは表示したい
- 「わかる!」などのアイコン表示してないときは顔アイコンを薄く大きく表示しておくとよいかも

**Comment by napo0703** [comment]
Twitterのアイコンは
http://140note.hitonobetsu.com/apipage/profileimage
で簡単にできそう。

**Comment by shokai** [comment]
どうぞ http://twiticon.herokuapp.com/

**Comment by shokai** [comment]
あれ、全部同じ大きさになっちゃってる

**Comment by shokai** [comment]
twiticonは16時間しか動かないので忘れてください

**Comment by napo0703** [comment]
#20 でやった。

**Comment by napo0703** [comment]
https://wakaruland.com/grid/?masui,napo0703,registakm,dorayaki0,kir1ca,K_Pst,ami_nosan,hkrit0,sasa_sfc
![](https://i.gyazo.com/24d15e35a85c1bb4bf0cf367865c887d.png)
