### ISSUE TITLE
汎用通知システムにする

### ISSUE THREAD

**Issue by masui** [napo0703/WakaruLand#18]
個人の一時的な感情 (e.g. 「わかる!」) だけでなく、個人の状況 (e.g. 「会議中」) やシステムの状況 (e.g. 「トイレが空いてる」「メール来てる」) なども同じように扱えるようにするとすごく汎用になって嬉しいかも

**Comment by masui** [comment]
汎用なのに原理が超簡単、みたいなのが良い

**Comment by masui** [comment]
- わかるらんどをサブディスプレイに表示しておくとすべての通知情報が一覧できる
- 会議などでは参加者の気持ちを一覧できる
- 電車では自分の意図を表示できる

**Comment by shokai** [comment]
SF感あっていい

**Comment by shokai** [comment]
もしかしてAndroidの通知欄+BLEでできたりする？

**Comment by shokai** [comment]
とりあえずデルタの電気ついたり消えたりしたらwakarulandにマルバツ送ってみるか

**Comment by shokai** [comment]
そこから電気をトグルらんどできるな

**Comment by masui** [comment]
汎用的すぎて起業せざるをえない

**Comment by masui** [comment]
pushでウザい通知を選択的に表示できるなら神なんじゃないかな

**Comment by masui** [comment]
WakaruLandというTupleSpaceに誰もが勝手に書き込むことにして、適当に選択して表示するページだけ用意すればいいのかも。
デルタの気温とか江ノ島の風速とか増井の血圧とか全部並べておける

**Comment by napo0703** [comment]
### タプルの仕様
- type
  - wakaruland
- who（人/物/現象）
  - napo
  - masui
  - delta_light
  - enoshima_wind
  - masui_blood_pressure
- value（リアクション、画像、数値など）
  - わかる
  - ⭕️
  - gyazo.com/24d15e35a85c1bb4bf0cf367865c887d.png
  - 2.8
  - 130
- displaytime（表示時間（秒））
  - 30
  - 3600
  - forever

**Comment by napo0703** [comment]
[18-notification-system](https://github.com/napo0703/WakaruLand/tree/18-notification-system) で実装中。

**Comment by shokai** [comment]
typeがwakarulandなの違和感ある
1つのリアクションや画像を表すのだからtype: wakariでは

**Comment by masui** [comment]
「who（人/物/現象）」というのは変では? IDならよいか?
IDが「@masui」ならtwitterの人物だと解釈し、「delta_light」とかならそういう名前の何かだと解釈する

**Comment by shokai** [comment]
fromなら名前やidか入ってそう

**Comment by masui** [comment]
from良いかも

**Comment by napo0703** [comment]
### タプルの仕様
- type（無くてもいい？？）
  - ~~wakaruland~~
  - wakari
- ~~who~~
- from（人/物/現象）
  - @napo0703
  - @masui
  - delta_light
  - enoshima_wind
  - masui_blood_pressure
- value（リアクション、画像、数値など）
  - わかる
  - ⭕️
  - gyazo.com/24d15e35a85c1bb4bf0cf367865c887d.png
  - 2.8
  - 130
- displaytime（表示時間（秒））
  - 30
  - 3600
  - forever

**Comment by masui** [comment]
- typeって何で必要なのかな?
- 研究室のいろんなセンサが統合されるのはアツいね
- displaytime = 0 なら forever でいいのでは

**Comment by masui** [comment]
タプル仕様は別issueにして、このissueは閉じたら?

**Comment by napo0703** [comment]
実装した
