### ISSUE TITLE
リアクションの表示時間を変えられるようにする

### ISSUE THREAD

**Issue by napo0703** [napo0703/WakaruLand#26]
現在は30秒間表示してるが、一覧から選んでリアクションするときに表示時間を選べるようにする。
とりあえず、
- クリック -> 30秒
- 長押し -> 30分
- 超長押し -> 消えない

で実装してみる。
表示時間は検討する。

**Comment by masui** [comment]
表示期間がわかるようにしてほしい。押してると色が変わっていくとか。

**Comment by masui** [comment]
数字が表示されればいいか

**Comment by shokai** [comment]
連打でもいい

**Comment by napo0703** [comment]
https://github.com/napo0703/WakaruLand/commit/7cc2fc6feabd4cae8adfba051a17e5e10195f5da で
- クリック -> 30秒
- 3秒以上長押し（背景青） -> 10分
- 5秒以上長押し（背景赤） -> 消えない

を実装しました。デプロイ済です。
使ってみて、もう少しクリック時間短くてもいいかなと思ってます。
表示時間も適当なのでご意見いただければ幸いです。

**Comment by masui** [comment]
- 5秒は長杉
- 時間はアナログに指定したい (3段階ではなく)

**Comment by napo0703** [comment]
#41 で議論。
