### ISSUE TITLE
ローカルで動かせない

### ISSUE THREAD

**Issue by shokai** [napo0703/WakaruLand#29]
![screen shot](https://gyazo.com/540e98f785532676f62a410e637c7d92.png)

**Comment by shokai** [comment]
localStorageが空なのにlocalStorageから名前をロードしてきてて、`undefined.substring(1)`を呼んで死んでる

**Comment by shokai** [comment]
ソースマップが無いからエラーコンソールにソースの行じゃなくてコンパイル後の行が出てる

**Comment by masui** [comment]
ローカルで動くものなの? herokuのLindaに接続可能?
(プルリクの修正反映させても動かないので)

**Comment by shokai** [comment]
@masui このアプリは全てクライアントサイド実装です
サーバーのコードはありません

**Comment by masui** [comment]
localhost:7070 とかどういう実装なんすか?

**Comment by shokai** [comment]
それ開発サーバーです

**Comment by masui** [comment]
ローカルでサーバが動くんじゃないんですか?

**Comment by masui** [comment]
BrowserSyncというのが勝手にサーバ立てるという理解でOK?

**Comment by shokai** [comment]
browser syncは私は使ったこと無いけど、有名なツールですね
ローカルで静的ファイルサーバーが起動し、複数のブラウザや端末で同じページを完全同期してスクロールやクリック等の操作ができるので表示やバグの確認に便利という物です
