### ISSUE TITLE
スマートフォンで長押しの認識ができてない

### ISSUE THREAD

**Issue by napo0703** [napo0703/WakaruLand#36]
こうなってしまう

![](https://i.gyazo.com/d73e49716e06675be032495c516a1215.png)

**Comment by shokai** [comment]
これ、根本的にスマホで長押しUIはやらないほうがいいって事な気がするんだけどどうなんだろう

**Comment by masui** [comment]
そうかもしれない。長押しやめますか。

**Comment by masui** [comment]
タップしたあとのドラッグ具合で時間を決めるとどうか? 何秒表示するかを
ドラッグで指定する。

**Comment by masui** [comment]
ドラッグで時計的な何かを操作することで表示時間を指定できると良さそう?

**Comment by shokai** [comment]
連打で表示時間が増える
1回、2回、3回で
10秒→100秒→1000秒

**Comment by masui** [comment]
preventDefault() ではダメなの?

**Comment by napo0703** [comment]
スマートフォンで長押しするとこのダイアログが出てしまうのは画像を長押ししているからです。
画像の上に透明なViewを用意すればスマートフォンでも問題なく使えるのではないかと思います。

**Comment by masui** [comment]
画像にpreventDefault()してもだめなんすか

**Comment by shokai** [comment]
スマホで長押しは編集やキャンセルだからなんか違う気がするなあ

**Comment by masui** [comment]
まぁ長押しにこだわるわけではないです。どういうのが良いかな?

**Comment by masui** [comment]
スライダで秒数指定するだけでもいいかも

**Comment by napo0703** [comment]
#46 で
