### ISSUE TITLE
Gyazo画像の利用

### ISSUE THREAD

**Issue by masui** [napo0703/WakaruLand#37]
- わかるらんどで画像を用意する必要は無いのでは?
- 「わかる」などのGyazo画像のURLだけデフォルトとして用意しておけば良いような
- ユーザは個人的に使うものを追加できるようにする

**Comment by masui** [comment]
テキスト表示機能も要らないと思う

**Comment by masui** [comment]
- 使う画像を自由に足したり消したりするといいかな
- index.js中にファイル名を書くのはやめたい

**Comment by shokai** [comment]
> 使う画像を自由に足したり消したりするといいかな

たぶん一番楽なのは
1. 使いたい画像のgyazoページでブックマークレット実行
   - `javascript:(function(){location.href='http://wakaruland.com/gyazo?url='+location.href+'.png'})();`
2. http://wakaruland.com/gyazo?url=http://gyazo.com/~~~.png に移動
   - ここで`localStorage.gyazo = []`に追加してしまう
3. wakaruland.comのトップで画像選択の中に`localStorage.gyazo`配列も追加して表示する

**Comment by shokai** [comment]
gyazoのコレクション機能を使えばいいかもしれないがAPIがまだ無いかも？

**Comment by napo0703** [comment]
[Gyazoのコレクションのフィード](https://gyazo.com/collections/d2842e2e9bbdb05b8b74dba5d5d35104) をajaxで読むために [jquery.xdomainajax.js](https://github.com/padolsey-archive/jquery.fn/blob/master/cross-domain-ajax/jquery.xdomainajax.js) を使いたいんですけどどこになんて書けばいいのん？

**Comment by Hikaru-Ito** [comment]
@napo0703 普通にjquery.xdomainajax.jsを読み込むだけでいいはずです。
jqueryのajaxが拡張されます。

**Comment by napo0703** [comment]
@Hikaru-Ito htmlに書くの？jsに書くの？

**Comment by Hikaru-Ito** [comment]
@napo0703 どっちでもいいです。
普通にhtmlから読み込めばいいと思います。

```
<script src="path/to/jquery.xdomainajax.js">
```

**Comment by toshiyukimasui** [comment]
Gyazoのコレクションは使わない方がいいと思います。
使ってる人は少ないだろうし。

**Comment by napo0703** [comment]
画像をURLで追加できるようになったよ
https://wakaruland.com
https://i.gyazo.com/38e7f7f269415974b63055e389f6c85e.png

**Comment by napo0703** [comment]
https://github.com/napo0703/WakaruLand/pull/42 で実装
