### ISSUE TITLE
投稿画面の設計

### ISSUE THREAD

**Issue by masui** [napo0703/WakaruLand#38]
こんな程度でどうか?
- 単独表示を行わない
- リアクションメニューをなくす
- 画像を足したり削除したり簡単にできるようにする
  - URLを入力して「+」を押すと追加される
  - 「-」を押すと現在選択中のものが削除される

![](https://gyazo.com/0777be792189b7d000ff91bd035592e4.png)

**Comment by napo0703** [comment]
https://github.com/napo0703/WakaruLand/pull/42 で実装。
こうなった。
![](https://i.gyazo.com/38e7f7f269415974b63055e389f6c85e.png)
