### ISSUE TITLE
表示時間の指定方法

### ISSUE THREAD

**Issue by masui** [napo0703/WakaruLand#41]
- 色だとわかりにくい
- アナログに指定できてもよいのでは? (e.g. 長押し時間×10秒間表示する)

**Comment by masui** [comment]
長押ししてるとスケールがだんだん上がってくる... みたいなのでどうですかね。大昔のゴルフゲームみたいな感じ。

**Comment by napo0703** [comment]
![](https://i.gyazo.com/87f32e209cd69d3d6a582843604ed5d5.gif)
