### ISSUE TITLE
Twitter認証の導入

### ISSUE THREAD

**Issue by napo0703** [napo0703/WakaruLand#43]
現在の仕様だと、例えば私が@masuiで発言することができてしまう。（悪く言うとなりすましができる）
特に害は無いのですが、**本当にその人がリアクションした**という証明のためにも認証を導入すべきだと思います。
TwitterのIDとアイコンをユーザ一覧の表示に使ってますし、Twitterの外部アプリ認証がいいのではないかと思うのですがいかがでしょう？
本人確認に使うだけで、もちろん勝手にツイートさせたりするわけじゃないです。

**Comment by toshiyukimasui** [comment]
メンドクサイから認証は要らないと思います...
認証なければ共有アカウント(?)とかだって作れるし

**Comment by napo0703** [comment]
今は閉じとこう
