### ISSUE TITLE
グリッド表示を起動したとき、現在投稿されてる画像を表示する

### ISSUE THREAD

**Issue by masui** [napo0703/WakaruLand#52]
初期画面しか出ないみたいなので

**Comment by napo0703** [comment]
一覧を表示した時に表示している人の最新のタプルをreadすればいいのかな？

**Comment by shokai** [comment]
> 一覧を表示した時に表示している人の最新のタプルをreadすればいいのかな？

それでいいはず。writeする時にexpireを付けて書き込むようにしないと、20秒で消えるつもりの人が21秒目でも表示されたり、3時間表示するつもりの人が表示されなかったりするので注意

`ts.write(data, {expire: 300})` これで300秒でtupleが消える

**Comment by napo0703** [comment]
タプルが書き込まれた時刻を取得することは可能ですか？
ts.wirte({date: "2016/7/7 17:57:50"}) とかしないとだめですか？

**Comment by napo0703** [comment]
あ、必要ないか

**Comment by napo0703** [comment]
@shokai linda-serverのことでいくつか質問です。
- クライアントでexpireイベントを取得できますか？
- 現時点でreadのキャンセル処理はどうやって書いたらいいですか？

**Comment by shokai** [comment]
> クライアントでexpireイベントを取得できますか？

できません

> 現時点でreadのキャンセル処理はどうやって書いたらいいですか？

`tuplespace.read`がreturnする`cancelId`を`tuplespace.cancel(cancelId)`すると、キャンセルできます
https://github.com/masuilab/slack-hubot/blob/master/scripts/linda.coffee#L33

**Comment by napo0703** [comment]
タプルが書き込まれた時刻って取得できますか？

**Comment by shokai** [comment]
無理どす

**Comment by shokai** [comment]
tupleのプロパティに付けて送るとよい

**Comment by napo0703** [comment]
#68
