### ISSUE TITLE
ボタンが多い

### ISSUE THREAD

**Issue by napo0703** [napo0703/WakaruLand#53]
![](https://i.gyazo.com/637f7655cf222eebaddd605df836ad5f.png)

どれがなんだかわからんど

**Comment by napo0703** [comment]
UIの再検討、見た目を整える、CSS力を補うという目的から、Bootstrapを導入しようと思います。

**Comment by masui** [comment]
そんなん要らないんじゃないかなぁ?
練習には良いかもしれないけど

**Comment by napo0703** [comment]
#55
