### ISSUE TITLE
リストを引数で指定

### ISSUE THREAD

**Issue by masui** [napo0703/WakaruLand#7]
http://wakaruland.com/masui,napo,shokai
みたいな感じ?

**Comment by napo0703** [comment]
#2 関連ですかね。
- どうやってグループを作るのか
- そのグループの中でどうやって自分の名前でリアクションするのか

を検討したいです。

**Comment by shokai** [comment]
名前を後ろにつけていくのって、後から人が増えたらURL変わってしまうから
学会等で使うのには向いてないのでは

**Comment by masui** [comment]
気軽にリスト指定できるのが良いと思うのですが。登録は面倒なので。

**Comment by masui** [comment]
好きな人だけリストしたいこともあるだろうし

**Comment by napo0703** [comment]
#15 で議論
