### ISSUE TITLE
表示したいWebカメラの映像

### ISSUE THREAD

**Issue by napo0703** [napo0703/WakaruLand#77]
逗子マリーナ
http://113.32.231.147/nphMotionJpeg?Resolution=320x240&Quality=Standard&Framerate=30

**Comment by isSatake** [comment]
ライブカメラまとめ
http://orange.zero.jp/zad23743.oak/livecam/

**Comment by shokai** [comment]
以前世界中のwebカメラをクロールしてリストしてるサイトがあったんだけど、URL忘れた

**Comment by napo0703** [comment]
4ef92a912a0292ed4979b34d651cfce78a7ea118 でユーザやセンサとかと同じようにMotion JPEGのURLをURL末尾に列挙すれば表示できるようにした。

https://wakaruland.com/?@napo0703,delta_light,http://masuilab.org:8765/videofeed,http://113.32.231.147/nphMotionJpeg
