### ISSUE TITLE
READMEをちゃんと書く

### ISSUE THREAD

**Issue by napo0703** [napo0703/WakaruLand#84]
- 概要
- 動作環境
- 基本的な使い方
  - 一覧するユーザの指定方法
  - ユーザの1人としてリアクションする方法
  - スタンプの追加方法
    - テキストスタンプ
    - 画像スタンプ
  - デスクトップアプリケーション
- FAQ
- 開発

**Comment by shokai** [comment]
単純な起動方法はREADME.mdに書くとして、コンセプトとかFAQは公開scrapboxを作ってそこに書くのも良いと思います

**Comment by napo0703** [comment]
とりあえず作った
https://scrapbox.io/wakaruland/
